config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  resources :reservations do
    member do
      post 'confirm' => 'reservations#confirm'
      post 'back' => 'reservations#back'
    end
  end

  resources :rooms do
    collection do
      get 'own'
    end
  end

  devise_for :users
  get 'users/account' => 'users#account'
  get 'users/profile' => 'users#profile'
  get 'users/profile/edit' => 'users#profile_edit'
  patch 'users/profile/update' => 'users#profile_update'
  root 'top#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :room
  has_many :reservation
  mount_uploader :image, ImageUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  #def new
    #super
  #end

  # POST /resource
  #def create
  #  super
  #end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
  end

  def profile

  end

  def profile_edit
    @user = User.find(current_user.id)
  end

  def profile_update
    @user = User.find(current_user.id)
    @user.update(params.require(:user).permit(:name,:profile,:image))
    redirect_to "/users/profile"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="container">
  <h2>設定</h2>
  <div class="user-container">
    <ul class="side-navigation">
      <li class="side-nav-item active"><a href="/users/account">アカウント</a></li>
      <li class="side-nav-item"><a href="/users/profile">プロフィール</a></li>
    </ul>
    <div class="account-info">
      <div class="account-title">
        <h2>アカウント</h2>
        <a class="acount-edit" href="/users/edit">編集</a>
      </div>
      <div class="account-info-group">
        <label class="account-label">メールアドレス</label>
        <p class="account-value"><%= current_user.email %></p>
      </div>
      <div class="account-info-group">
        <label class="account-label">パスワード</label>
        <p class="account-value">*********</p>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container">
  <h2>設定</h2>
  <div class="user-container">
    <ul class="side-navigation">
      <li class="side-nav-item"><a href="/users/account">アカウント</a></li>
      <li class="side-nav-item active"><a href="/users/profile">プロフィール</a></li>
    </ul>
    <div class="account-info">
      <div class="account-title">
        <h2>プロフィール</h2>
        <a class="acount-edit" href="/users/profile/edit">編集</a>
      </div>
      <div class="account-info-group">
        <label class="account-label">アイコン画像</label>
        <p class="account-value"><%= image_tag current_user.image.blank? ? 'default-avatar' : current_user.image.url %></p>
      </div>
      <div class="account-info-group">
        <label class="account-label">名前</label>
        <p class="account-value"><%= current_user.name %></p>
      </div>
      <div class="account-info-group">
        <label class="account-label">自己紹介</label>
        <p class="account-value"><%= current_user.profile%></p>
      </div>
    </div>
  </div>
</div>

app/views/users/profile_edit.html.erb
<div class = "form-container container">
  <h4>プロフィール編集</h4>

  <%= form_with model:@user,url: users_profile_update_path ,class: "row g-3" do |f|%>
    <div class = "col-12">
      <%= f.label :image,"アイコン画像",class: "form-label"%>
      <%= f.file_field :image , class:"form-control "%>
    </div>
    <div class = "col-12">
      <%= f.label :name,"名前" ,class: "form-label"%>
      <%= f.text_field :name, class:"form-control"%>
    </div>
    <div class = "col-12">
      <%= f.label :profile,"自己紹介",class: "form-label"%>
      <%= f.text_area :profile , class:"form-control"%>
    </div>
    <div class = "w-100 mt-2 pr-3 d-flex justify-content-end">
      <a href = "/users/profile"><button type = "button" class="btn btn-secondary">キャンセル</button></a>
      <%= f.submit "保存", class:"btn btn-primary ml-1"%>
    </div>
  </form>

</div>
<% end %>