config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  resources :reservations do
    member do
      post 'confirm' => 'reservations#confirm'
      post 'back' => 'reservations#back'
    end
  end

  resources :rooms do
    collection do
      get 'own'
    end
  end

  devise_for :users
  get 'users/account' => 'users#account'
  get 'users/profile' => 'users#profile'
  get 'users/profile/edit' => 'users#profile_edit'
  patch 'users/profile/update' => 'users#profile_update'
  root 'top#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :checkin, presence: true
  validates :checkout, presence: true
  validates :numberpeople, presence: true,numericality: true
  validate :start_end_check


  belongs_to :room
  belongs_to :user

  def start_end_check
    if (self.checkin != nil && self.checkout != nil)
      errors.add(:checkout, "はチェックインより後に登録してください") unless
      self.checkin < self.checkout
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def confirm
    @reservation = Reservation.new(params.require(:reservation).permit(:checkin,:checkout,:user_id,:room_id,:numberpeople))
    @room = Room.find(@reservation.room_id)
    @user = User.find(current_user.id)
    if @reservation.valid?
      day = @reservation.checkout - @reservation.checkin
      @days = day.to_i
      @cost = @room.price * @reservation.numberpeople * @days
    else
      flash[:warning] = "予約内容に誤りがあります"
      render "/rooms/show"
    end
  end

  def create
    @reservation = Reservation.new(params.require(:reservation).permit(:checkin,:checkout,:user_id,:room_id,:numberpeople))
    if @reservation.save
      redirect_to "/reservations"
    else
      render "/reservations/confirm"
    end
  end

  def back
    @reservation = Reservation.new(params.require(:reservation).permit(:checkin,:checkout,:user_id,:room_id,:numberpeople))
    @room = Room.find(@reservation.room_id)
    @user = User.find(@reservation.user_id)
    render "/rooms/show"
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.html.erb
<div class="FormWrapper container">
  <h2 class="confirm-title">予約確認</h2>
  <dl>
		<div class="confirm-value-group">
			<dt class="confirm-label">チェックイン</dt>
			<dd class="confirm-value"><%= @reservation.checkin %></dd>
		</div>
		<div class="confirm-value-group">
			<dt class="confirm-label">チェックアウト</dt>
			<dd class="confirm-value"><%= @reservation.checkout %></dd>
		</div>
		<div class="confirm-value-group">
			<dt class="confirm-label">人数</dt>
			<dd class="confirm-value"><%= @reservation.numberpeople %></dd>
		</div>
		<div class="confirm-value-group">
    	<dt class="confirm-label">日数</dt>
    	<dd class="confirm-value"><%= @days %></dd>
		</div>
		<div class="confirm-value-group">
    	<dt class="confirm-label">価格</dt>
    	<dd class="confirm-value confirm-price"><%= @cost %>円</dd>
		</div>
	</dl>

	<%= form_for @reservation, method: :post,url: reservations_path do |f|%>
    <%= f.hidden_field :checkin %>
		<%= f.hidden_field :checkout %>
		<%= f.hidden_field :numberpeople %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :room_id %>
		<%= f.submit '予約を確定' ,class: "btn confirm-submit"%>
	<% end %>
	<%= form_for @reservation, url: back_reservation_path do |f| %>
		<%= f.hidden_field :checkin %>
		<%= f.hidden_field :checkout %>
		<%= f.hidden_field :numberpeople %>
  	<%= f.hidden_field :user_id %>
  	<%= f.hidden_field :room_id %>
		<%= f.submit 'キャンセル' ,class: "btn confirm-cancel"%>
	<% end %>
</div>

app/views/reservations/index.html.erb
<div class = "container w-auto">
  <div class="page-title">
    <h4>予約済み一覧</h4>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>画像</th>
        <th>施設名</th>
        <th>紹介文</th>
        <th>合計金額</th>
        <th>チェックイン</th>
        <th>チェックアウト</th>
        <th>人数</th>
        <th>作成日</th>
      </tr>
    </thead>

    <tbody>
    <% @reservations.each do |reservation| %>
    <% room = Room.find(reservation.room_id)%>
    <% day = reservation.checkout - reservation.checkin %>
    <% days = day.to_i %>
    <% cost = room.price * days * reservation.numberpeople %>
    <tr>
      <td class="w-25"><%= image_tag room.image.blank? ? 'default-image' : room.image.url ,class: "w-100"%></td>
      <td><%= room.name%></td>
      <td><%= room.introduction%></td>
      <td><%= cost %></td>
      <td><%= reservation.checkin %></td>
      <td><%= reservation.checkout %></td>
      <td><%= reservation.numberpeople %></td>
      <td><%= reservation.created_at.strftime("%Y/%m/%d %H:%M") %></td>
    </tr>
  </tr>
  <% end %>
</tbody>
</table>

</div>