config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  resources :reservations do
    member do
      post 'confirm' => 'reservations#confirm'
      post 'back' => 'reservations#back'
    end
  end

  resources :rooms do
    collection do
      get 'own'
    end
  end

  devise_for :users
  get 'users/account' => 'users#account'
  get 'users/profile' => 'users#profile'
  get 'users/profile/edit' => 'users#profile_edit'
  patch 'users/profile/update' => 'users#profile_update'
  root 'top#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true,numericality: true
  validates :address, presence: true
  has_many :reservation
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index

    if params[:search_area] != "" || params[:search_keyword] != ""
      @rooms = Room.where("address LIKE? AND name LIKE?", "%#{params[:search_area]}%","%#{params[:search_keyword]}%")
    else
      @rooms = Room.all
    end

  end

  def own
    @rooms = Room.where(user_id: current_user.id)
  end
  
  def new
    @user = User.find(current_user.id)
    @room = Room.new
  end

  def create
    @user = User.find(current_user.id)
    @room =  Room.new(params.require(:room).permit(:name,:introduction,:price,:user_id,:address,:image))
    if @room.save
      flash[:success] = "施設を登録しました"
      redirect_to "/rooms/own"
    else
      flash[:warning] = "施設の登録に失敗しました"
      render "rooms/new"
    end
  end

  def show
    @reservation = Reservation.new
    @room= Room.find(params[:id])
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

  def edit
    @room = Room.find(params[:id])
    @user = User.find(current_user.id)
  end

  def update
    @room = Room.find(params[:id])
    @user = User.find(current_user.id)
    if @room.update(params.require(:room).permit(:name,:introduction,:price,:user_id,:address,:image))
      flash[:success] = "施設を編集しました"
      redirect_to "/rooms/own"
    else
      flash[:warning] = "施設の登録に失敗しました"
      render "rooms/edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:success] = "施設を削除しました"
    redirect_to "/rooms/own"
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class = "form-container container">
  <h4>施設の編集</h4>

  <%= form_with model:@room, class: "row g-3" do |f|%>
    <div class = "col-12">
      <%= f.label :name,"施設名" ,class: "form-label"%>
      <%= f.text_field :name, class:"form-control"%>
    </div>
    <div class = "col-12">
      <%= f.label :address,"住所",class: "form-label"%>
      <%= f.text_field :address , class:"form-control"%>
    </div>
    <div class = "col-12">
      <%= f.label :introduction,"施設詳細",class: "form-label"%>
      <%= f.text_area :introduction , class:"form-control"%>
    </div>
    <div class = "col-12">
      <%= f.label :price,"価格",class: "form-label"%>
      <%= f.text_field :price , class:"form-control"%>
    </div>
    <div class = "col-12">
      <%= f.label :image,"イメージ画像",class: "form-label"%>
      <%= f.file_field :image , class:"form-control"%>
    </div>
    <%= f.hidden_field :user_id, value: @user.id %>
    <div class = "w-100 mt-2 pr-3 d-flex justify-content-end">
      <a href = "/rooms/own"><button type = "button" class="btn btn-secondary">キャンセル</button></a>
      <%= f.submit "保存", class:"btn btn-primary ml-1"%>
    </div>
  </form>
    <%= render "shared/error", obj: @room %>
</div>
<% end %>

app/views/rooms/index.html.erb
  <div class="index-form">
    <%= form_with url: rooms_path,method: :get, local: true do |f| %>
      <%= f.text_field :search_area, placeholder: "エリア名を入力",class: "form-group"%>
      <%= f.text_field :search_keyword, placeholder: "キーワードを入力",class: "form-group"%>
      <%= f.submit "検索" ,class: "btn btn-primary"%>
    <% end %>
  </div>
  <p class="data-count"><%= @rooms.count%>件見つかりました。</p>
  <ul class ="room-list">
    <% @rooms.each do |room| %>
    <li class="room">
      <%= image_tag room.image.blank? ? 'default-image' : room.image.url, class: "room-img"%>
      <div class="room-wapper">
        <p class="room-name"><%= room.name %></p>
        <p class="room-address"><%= room.address %></p>
        <p class="room-introduction"><%= room.introduction %></p>
        <p class="room-price">¥<%= number_to_currency(room.price, precision: 0) %>~</p>
        <%= link_to "詳細はこちら",room,class: "room-btn"%>
      </div>
    </li>
    <% end %>
  </ul>

app/views/rooms/new.html.erb
<div class = "form-container container">
  <h4>施設の新規追加</h4>

  <%= form_with model:@room, class: "row g-3" do |f|%>
    <div class = "col-12">
      <%= f.label :name,"施設名" ,class: "form-label"%>
      <%= f.text_field :name, class:"form-control"%>
    </div>
    <div class = "col-12">
      <%= f.label :address,"住所",class: "form-label"%>
      <%= f.text_field :address , class:"form-control"%>
    </div>
    <div class = "col-12">
      <%= f.label :introduction,"施設詳細",class: "form-label"%>
      <%= f.text_area :introduction , class:"form-control"%>
    </div>
    <div class = "col-12">
      <%= f.label :price,"価格",class: "form-label"%>
      <%= f.text_field :price , class:"form-control"%>
    </div>
    <div class = "col-12">
      <%= f.label :image,"イメージ画像",class: "form-label"%>
      <%= f.file_field :image , class:"form-control"%>
    </div>
    <%= f.hidden_field :user_id, value: @user.id %>
    <div class = "w-100 mt-2 pr-3 d-flex justify-content-end">
      <a href = "/rooms/own"><button type = "button" class="btn btn-secondary">キャンセル</button></a>
      <%= f.submit "保存", class:"btn btn-primary ml-1"%>
    </div>
  </form>
    <%= render "shared/error", obj: @room %>
</div>
<% end %>

app/views/rooms/own.html.erb
<div class = "container w-auto">
  <div class="page-title mt-2">
    <h4>登録済み一覧</h4>
  </div>
  <table class="table align-middle OwnRoomsTable">
    <thead>
      <tr>
        <th>画像</th>
        <th>施設名</th>
        <th>住所</th>
        <th>紹介文</th>
        <th>料金</th>
        <th>作成日</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    <% @rooms.each do |room| %>
    <tr>
      <td class="w-25"><%= image_tag room.image.blank? ? 'default-image' : room.image.url ,class: "w-100"%></td>
      <td><%= link_to "#{room.name}",room,method: :get,class: "text-primary"%></td>
      <td><%= room.address %></td>
      <td><%= room.introduction %></td>
      <td><%= number_to_currency(room.price, :unit => "￥",:precision => 0) %>~</td>
      <td><%= room.created_at.strftime("%Y/%m/%d")  %></td>
      <td>
      <a class="nav-link dropdown-toggle text-primary" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropdownMenuLink"></a>
      <div class="dropdown-menu">
        <a class="dropdown-item text-primary" href="/rooms/<%= room.id %>/edit">編集</a>
        <%= link_to "削除",room, method: :delete, data: { confirm: "本当に削除しますか？" },class: "dropdown-item text-primary" %>
      </div>
      </td>
    </tr>
  </tr>
  <% end %>
</tbody>
</table>

</div>

app/views/rooms/show.html.erb
<div class="back container">
 <%= link_to "← 戻る",:back, class: "back-link "%>
</div>

<div class="room-show container">

  <%= image_tag @room.image.blank? ? 'default-image' : @room.image.url ,class: "show-img"%>
  <div class="show-body">
    <div class="name-price">
      <p class="show-name"><%= @room.name %></p>
      <p class="show-price">¥<%= number_to_currency(@room.price,precision: 0) %>~</p>
    </div>
    <p class="show-address"><%= @room.address %></p>
    <p class="show-intro"><%= @room.introduction %></p>
  <%if user_signed_in?%>
    <div class="reservation-form">
      <%= form_with model:@reservation, url: confirm_reservation_path do |f|%>
      <div>
        <%= f.label :checkin,"チェックイン" ,class: "form-label"%>
        <%= f.date_field :checkin, class:"form-control"%>
      </div>
      <div>
        <%= f.label :checkout,"チェックアウト",class: "form-label"%>
        <%= f.date_field :checkout , class:"form-control"%>
      </div>
      <div>
        <%= f.label :numberpeople,"人数",class: "form-label"%>
        <%= f.number_field :numberpeople ,min: 1, class:"form-control"%>
      </div>
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.hidden_field :room_id, value: @room.id%>
      <div class = "w-100 mt-2 pr-3 d-flex justify-content-end">
        <%= f.submit "送信", class:"btn btn-primary ml-1"%>
      </div>
      <% end %>
    </div>
  </div>
  <% else %>
  <div class="reservation-form">
      <%= form_with model:@reservation, url: confirm_reservation_path do |f|%>
      <div>
        <%= f.label :checkin,"チェックイン" ,class: "form-label"%>
        <%= f.date_field :checkin, class:"form-control"%>
      </div>
      <div>
        <%= f.label :checkout,"チェックアウト",class: "form-label"%>
        <%= f.date_field :checkout , class:"form-control"%>
      </div>
      <div>
        <%= f.label :numberpeople,"人数",class: "form-label"%>
        <%= f.number_field :numberpeople ,min: 1, class:"form-control"%>
      </div>
      <div class = "w-100 mt-2 pr-3 d-flex justify-content-end">
        <%=link_to "ログイン", new_user_session_path,class:"btn btn-primary ml-1"%>
      </div>
      <% end %>
    </div>
  <% end %>
</div>